### PR TITLE
Reduce webpack.tests.js

### PR DESCRIPTION
**Pull request by MoOx**
Feel free to close without merging if you have any reasons to.

### CODE REVIEW

**Comment by bloodyowl** [comment]
please just use a variable for the array. I don't want the line to start with `[` or `(`

**Comment by MoOx** [comment]
haha. Good idea.
Note: it seems this script doesn't handle new files (you might create during developments).

**Comment by MoOx** [comment]
variable added.

**Comment by MoOx** [comment]
that was fast :)

**Comment by bloodyowl** [comment]
thanks!

**Pull request merged**
